name: ci

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v7
            - name: Set up Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: "26"
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
    vv:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: vv1
              run: echo "Vali is awesome!"
