name: Contexts

on: workflow_dispatch

permissions: {}

jobs:
    "show_github_actor":
        runs-on: ubuntu-latest

        steps:
            - name: Show Github Actor
              env:
                  ACTOR: ${{ github.actor }}
              run: |
                  echo "$ACTOR"
            - name: "Show Runner Info"
              env:
                  OS: ${{ runner.os }}
                  NAME: ${{ runner.name }}
              run: |
                  echo "OS: $OS"
                  echo "Runner Name: $NAME"
