name: Contexts

on: workflow_dispatch

permissions: {}

env:
    COLOR: red

jobs:
    show_context:
        name: Show context
        runs-on: ubuntu-latest

        steps:
            - id: show_github_actor
              name: Show Github Actor
              env:
                  ACTOR: ${{ github.actor }}
              run: |
                  echo "$ACTOR"
                  echo "$COLOR"

            - name: Show Runner Info
              env:
                  OS: ${{ runner.os }}
                  NAME: ${{ runner.name }}
                  COLOR: blue
              run: |
                  echo "OS: $OS"
                  echo "Runner Name: $NAME"
                  echo "COLOR: $COLOR"

            - name: Show vars
              env:
                  APP_ENV: ${{ vars.APP_ENV }}
              run: |
                  echo "APP_ENV: $APP_ENV"

            - name: Show secret
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              run: |
                  echo "DB_PASSWORD: $DB_PASSWORD"
                  echo "parola-de-test-123"

            - name: Show step outcome
              env:
                  STEP_OUTCOME: ${{ steps.show_github_actor.outcome }}
                  JOB_STATUS: ${{ job.status }}
              run: |
                  echo "STEP_OUTCOME: $STEP_OUTCOME"
                  echo "JOB_STATUS: $JOB_STATUS"
    needs:
        needs: show_context
        name: Needs context
        runs-on: ubuntu-latest

        steps:
            - name: Show Needs Build Result
              env:
                  BUILD_RESULT: ${{needs.show_context.result}}
              run: |
                  echo "Build was: $BUILD_RESULT"

    matrix:
        name: Matrix
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        steps:
            - name: Show runner os
              env:
                  RUNNER_OS: ${{ runner.os }}
              run: |
                  echo "RUNNER_OS: $RUNNER_OS"

            - name: Show job index
              env:
                  JOB_INDEX: ${{ strategy.job-index }}
              run: |
                  echo "JOB_INDEX: $JOB_INDEX"

            - name: Show job total
              env:
                  JOB_TOTAL: ${{ strategy.job-total }}
              run: |
                  echo "JOB_TOTAL: $JOB_TOTAL"
