name: Hello GitHub Actions Lab

on:
  workflow_dispatch:
    inputs:
      recipient:
        description: "Who should be greeted?"
        required: true
        type: string
        default: "World"

permissions: {}

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        env:
          RECIPIENT: ${{ inputs.recipient }}
        run: echo "Hello $RECIPIENT!"
